sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
if: commit_message !~ /(Automatic-Release)/
before_script:
  - export APP_VERSION=$(bash contrib/new-version.sh)
  - mvn versions:set -DnewVersion=$APP_VERSION
before_deploy:
  - git config --local user.name "avengerweb"
  - git config --local user.email "i@avenger-web.com"
  - git add pom.xml
  - git commit -m "[Automatic-Release] New version $APP_VERSION"
  - git tag "$APP_VERSION"
  - "git push origin HEAD:$TRAVIS_BRANCH"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - "target/sirus-launcher-${APP_VERSION}.exe"
  skip_cleanup: true
  on:
    branch: master
    tags: false